### ISSUE TITLE
Concrete5 version doesn't match in composer.json and package controller

### ISSUE THREAD

**Issue by Kaapiii** [concrete5cojp/open_graph_tags_lite#25]
In the package.json minimal concrete5 version is 5.7.4 and in the package controller the minimal concrete5 version is marked as ^8.5"

**Comment by hissy** [comment]
This package supports 5.7.4+. However, installing concrete5 via composer is supported since version 8. So you can't install this package via composer on 5.7.x.

**Comment by Kaapiii** [comment]
Makes sense. :)
