### ISSUE TITLE
Package not installable with composer if c5 wasn't installed with "composer create-project"

### ISSUE THREAD

**Issue by Kaapiii** [concrete5cojp/open_graph_tags_lite#26]
The package can only be installed with composer on concrete5 sites which were created with `composer create-project -n concrete5/composer`. If I try to require this package from packagist.org on an website which was installed with a official concrete5 download, composer throws the following error:

```bash
Problem 1
    - Installation request for concrete5/concrete5 No version set (parsed as 1.0.0) -> satisfiable by concrete5/concrete5[No version set (parsed as 1.0.0)].
    - concrete5cojp/open_graph_tags_lite 2.1.4 requires concrete5/core ^8.5 -> satisfiable by concrete5/core[8.5.0, 8.5.1, 8.5.2].
    - don't install concrete5/core 8.5.0|remove concrete5/concrete5 No version set (parsed as 1.0.0)
    - don't install concrete5/core 8.5.1|remove concrete5/concrete5 No version set (parsed as 1.0.0)
    - don't install concrete5/core 8.5.2|remove concrete5/concrete5 No version set (parsed as 1.0.0)
    - Installation request for concrete5cojp/open_graph_tags_lite ^2.1 -> satisfiable by concrete5cojp/open_graph_tags_lite[2.1.4].
```

I guess it's because of the following line in the composer.json file: [Line](https://github.com/concrete5cojp/open_graph_tags_lite/blob/3d7dffd3bf26e2b51ee0cfcba005ef15d8ab2fa8/composer.json#L9)

**Comment by hissy** [comment]
Yes, you can install concrete5 packages with composer only when you installed concrete5 with composer too. Please check Korvin's sample package.

https://github.com/concrete5/sample_composer_package/blob/658c24bb96ca6e1d4d448a8d84c44e5bb817c69f/composer.json#L7-L9

**Comment by Kaapiii** [comment]
Well, concrete5 packages also can be installed with composer, even the installation wasn't created with `composer create`, since the downloadable package contains the composer.json file. (I've done so since v5.7) But I see what you mean.

**Comment by hissy** [comment]
Really? I didn't know we can c5 packages an install with composer now.
